services:

  nginx:
    build: nginx/.
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - django
    environment:
      HOST_NAME: ${HOST_NAME}
    volumes:
      - staticfiles:/staticfiles


  django:
    build: django/.
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      cp staticfiles/* /staticfiles/ -r &&
      rm staticfiles -rf &&
      daphne mewray.asgi:application -b 0.0.0.0 -p 8000
      "
    volumes:
      - ./django:/mewray
      - staticfiles:/staticfiles
    ports:
      - "8000:8000"
    environment:
      MEWRAY_DEBUG: "0"
      HOST_NAME: ${HOST_NAME}

  celery_worker:
    build: django/.
    container_name: celery_worker
    command: ["celery", "-A", "core", "worker", "--loglevel=info"]
    volumes:
      - ./django:/mewray
    depends_on:
      - django

  celery_beat:
    build: django/.
    container_name: celery_beat
    command: ["celery", "-A", "core", "beat", "--loglevel=info"]
    volumes:
      - ./django:/mewray
    depends_on:
      - django

volumes:
  staticfiles: