services:

  nginx:
    build: nginx/.
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - django
      - flower
    environment:
      HOST_NAME: ${HOST_NAME}
    volumes:
      - staticfiles:/staticfiles

  django:
    build: django/.
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      cp staticfiles/* /staticfiles/ -r &&
      rm staticfiles -rf &&
      daphne mewray.asgi:application -b 0.0.0.0 -p 8000
      "
    volumes:
      - ./django:/mewray
      - staticfiles:/staticfiles
    environment:
      MEWRAY_DEBUG: ${MEWRAY_DEBUG}
      HOST_NAME: ${HOST_NAME}
      REDIS_CONNECTION: "redis://redis:6379"
    depends_on:
      - redis

  celery_worker:
    build: django/.
    container_name: celery_worker
    command: ["celery", "-A", "core", "worker", "--loglevel=info"]
    volumes:
      - ./django:/mewray
    depends_on:
      - django
      - redis
    environment:
      REDIS_CONNECTION: "redis://redis:6379"
      MEWRAY_DEBUG: ${MEWRAY_DEBUG}

  celery_beat:
    build: django/.
    container_name: celery_beat
    command: ["celery", "-A", "core", "beat", "--loglevel=info"]
    volumes:
      - ./django:/mewray
    depends_on:
      - django
      - redis
    environment:
      MEWRAY_DEBUG: ${MEWRAY_DEBUG}
      REDIS_CONNECTION: "redis://redis:6379"

  flower:
    build: django/.
    container_name: flower
    command: ["celery", "-A", "core", "flower", "--port=8000"]
    depends_on:
      - redis
      - celery_worker
      - celery_beat
    environment:
      MEWRAY_DEBUG: ${MEWRAY_DEBUG}
      REDIS_CONNECTION: "redis://redis:6379"
    ports:
      - 8001:8000

  redis:
    image: redis:alpine
    container_name: resis
    ports:
      - 6379:6379

volumes:
  staticfiles: