from repo import models

backends = []

class baseNodeBackend:
    def __init__(self, node:models.node):
        self.address = node.address
        self.host = node.host
        self.auth = node.auth
        self.setting = node.settings
        self.dbObj = node
    async def aadd(self, uuid):...
    async def aremove(self, uuid):...
    async def aexists(self, uuid):...
    async def aisEnable(self, uuid):...
    async def aenable(self, uuid):...
    async def adisable(self, uuid):...
    async def atraffic(self, uuid):...
    async def aconfig(self, uuid):...
    async def aall(self):...
    def __init_subclass__(cls) -> None:
        backends.append(cls)

class AssignNotSynced(Exception):
    def __init__(self, uuid, *args: object) -> None:
        self.uuid = uuid
        super().__init__(*args)