# Generated by Django 5.1.1 on 2024-09-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='uuid',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='api_pk',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='view_pk',
            field=models.CharField(max_length=36),
        ),
    ]
