# Generated by Django 5.1.1 on 2024-10-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_alter_assign_uuid_alter_subscribe_api_pk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
