# Generated by Django 5.1.1 on 2024-11-11 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_subscribe_enable_alter_node_id_alter_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='subscribe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repo.subscribe'),
        ),
    ]
